---
- hosts: mywebservers
  become: yes
  tasks:
  
  - name: openjdk-11-jdk
    state: present
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
    when: ansible_os_family == "Debian"

  - name: install java on redhat
    dnf:
      name: "{{myjavapackonredhat}}"
      state: present
    when: ansible_os_family == "RedHat"

