---
- hosts: 172.31.2.7
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver
    apt:
      name: apache2
      state: present
  
  - name: copy my test file into node side
    copy:
      src: mytestfile
      dest: /home/ubuntu